#!/usr/bin/env bash
# Displays information about subdomains

subdomain_arr=('www' 'lb-01' 'web-01' 'web-02')

display () {
    if [[ $1 && ! $2 ]]; then
	domain="$1"
	for subdomain in "${subdomain_arr[@]}"
	do
	    record=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
	    destination=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
	    #shellcheck disable=SC2086
	    echo The subdomain $subdomain is a $record record and points to $destination
	done
    elif [[ $1 && $2 ]]; then
	domain="$1"
	subdomain="$2"
	record=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
	destination=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
	#shellcheck disable=SC2086
	echo The subdomain $subdomain is a $record record and points to $destination
    fi
}
if [[ $1 && ! $2 ]]; then
    #shellcheck disable=SC2086 
    display $1
elif [[ $1 && $2 ]]; then
    #shellcheck disable=SC2086 
    display $1 $2
fi
