#!/usr/bin/env bash
# This script Installs and configures HAproxy on your lb-01 server
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy

if ! sudo grep -q "backend web-backend" /etc/haproxy/haproxy.cfg; then
    echo -e "backend web-backend\n\tbalance roundrobin\n\tserver 531156-web-01 52.90.0.3 check\n\tserver 531156-web-02 54.210.51.202 check" >> /etc/haproxy/haproxy.cfg
fi

if ! sudo grep -q "frontend http" /etc/haproxy/haproxy.cfg; then
    echo -e "frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"  >> /etc/haproxy/haproxy.cfg
fi

if ! sudo grep -q "ENABLED=1" /etc/default/haproxy; then
    echo "ENABLED=1" >> /etc/default/haproxy
fi

sudo service haproxy restart
