#!/usr/bin/env bash
# Fixing what’s keeping Ubuntu container’s Nginx installation from listening on port 80
rm /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx restart
