#!/usr/bin/env bash
# Fixing what’s keeping Ubuntu container’s Nginx installation from listening on port 80
rm /etc/nginx/sites-available/default
echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
}' > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx restart
